Pablo/port createtileobjecttool
jessetrem/tiled pull request #2
Opened 2023-10-11 21:38 UTC by azagaya

2023-10-11 22:21 UTC, jessetrem requested changes

2023-10-11 22:21 UTC, jessetrem commented on src/tiled/propertybrowser.cpp
> +        if (obj == mObject || obj->wasRandomized())
Could you get these in // EDEN CHANGE blocks just to keep things consistent.

2023-10-11 22:21 UTC, jessetrem commented on src/tiled/tilestamp.h
> +    TileLayer *tileLayer() const;
// EDEN CHANGE pls

2023-10-11 22:21 UTC, jessetrem commented on src/tiled/createtileobjecttool.h
> +    /// <summary>
Pretty sure I made this mistake, could we also get this surrounded with `// EDEN CHANGE` and get rid of the `/// <summary>`

2023-10-11 22:21 UTC, jessetrem commented on src/tiled/createtileobjecttool.cpp
> +    useStamp = false;
Missing // EDEN CHANGE

2023-10-12 12:59 UTC, azagaya commented on src/tiled/tilestamp.h
> +    TileLayer *tileLayer() const;
I think this is unused? maybe we can just remove it?

2023-10-12 13:06 UTC, azagaya commented on src/tiled/tilestamp.h
> +    TileLayer *tileLayer() const;
Just left it there to be sure

2023-10-12 13:41 UTC, jessetrem approved these changes

2023-10-12 13:42 UTC, merged